name: Slow cache example
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:


  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: generate large file to cache
        run: dd if=/dev/urandom of=some-large-file bs=1M count=500
      - name: cache large file
        uses: actions/cache@v3
        with:
          path: some-large-file
          key: large-file
  restore-linux:
    name:  restore-linux
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: restore cached large file
        uses: actions/cache@v3
        with:
          path: some-large-file
          key: large-file
  restore-macos:
    name:  restore-macos
    needs: generate
    runs-on: macos-12
    steps:
      - name: restore cached large file
        uses: actions/cache@v3
        with:
          path: some-large-file
          key: large-file
